### ISSUE TITLE
Confusing debug message in the logs

### ISSUE THREAD

**Issue by nkoroste** [robolectric/robolectric-bazel#6] opened 2019-11-21 19:05 UTC
Are the following 2 debug messages actionable? should I don something to get rid of them?

```
INFO: SHA256 (https://github.com/robolectric/robolectric-bazel/archive/4.1.tar.gz) = 2ee850ca521288db72b0dedb9ecbda55b64d11c470435a882f8daf615091253d
DEBUG: Rule 'robolectric' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "2ee850ca521288db72b0dedb9ecbda55b64d11c470435a882f8daf615091253d"
DEBUG: Call stack for the definition of repository 'robolectric' which is a http_archive (rule definition at /home/nk/.cache/bazel/_bazel_nk/2007fbffc9ead87bb25ae587ecaccc95/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
 - /home/nk/Snapchat/Dev/android/snapchat/WORKSPACE:88:1
```

Workspace:
```
#### Robolectric Support
# Pulls in the maven_jar rules needed for Robolectric
http_archive(
    name = "robolectric",
    strip_prefix = "robolectric-bazel-4.1",
    urls = ["https://github.com/robolectric/robolectric-bazel/archive/4.1.tar.gz"],
)

load("@robolectric//bazel:robolectric.bzl", "robolectric_repositories")

robolectric_repositories()
```

**Comment by satyarths** [comment] 2019-12-26 07:12
Bazel can ensure reproducible builds if you add the `sha256` values for the archives you are downloading. You could specify the `sha256` values to get ride of these messages.
```
http_archive(
 name = "robolectric",
 urls = ["https://github.com/robolectric/robolectric-bazel/archive/4.1.tar.gz"],
 strip_prefix = "robolectric-bazel-4.1",
 sha256 = "2ee850ca521288db72b0dedb9ecbda55b64d11c470435a882f8daf615091253d"
)
```

**Comment by utzcoz** [comment] 2022-10-09 09:30
Looks like that adding sha256 can remove mentioned messages. I will close it, and feel free to reopen it if you have any questions.

**Closed by utzcoz** 2022-10-09 09:30 UTC
